env:
    GH_TOKEN: ENCRYPTED[c4bb0e3f71ae05d66212a1a2df9be6b8e106cd4b5e288de51d909560f47b97e809f942fe310adacdd4f429fdee3f1147]

task:
  name: LLVM Toolchain
  timeout_in: 120m
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Get-deps_script:
       - bash ci.sh deps

  Deploy-builder_script:
      - bash build.sh
