env:
    GH_TOKEN: ENCRYPTED[a1e1b1cb57b63cad7e5cd52cccf152f13120b4b7855ad08d069fa178266618946a53202ed150a2ccdc25f3d522894c42]

task:
  name: LLVM Toolchain
  timeout_in: 120m
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Get-deps_script:
       - bash ci.sh deps

  Deploy-builder_script:
      - bash build.sh
